sudo: required

services:
  - docker

env:
  - IMAGE=ubuntu:rolling
  - IMAGE=fedora:latest

language: c

script:
  - docker pull $IMAGE
  - cid=`docker run --tty --detach --volume $TRAVIS_BUILD_DIR:/lightdm --workdir /lightdm $IMAGE bash`
  - if [ $IMAGE = "ubuntu:rolling" ]; then docker exec $cid apt-get update; fi
  - if [ $IMAGE = "ubuntu:rolling" ]; then docker exec $cid apt-get install -y --no-install-recommends gtk-doc-tools intltool libaudit-dev libgcrypt20-dev libgirepository1.0-dev libglib2.0-dev libpam0g-dev libqt4-dev libtool libxcb1-dev libxdmcp-dev libxklavier-dev qtbase5-dev valac yelp-tools; fi
  - if [ $IMAGE = "fedora:latest" ]; then docker exec $cid dnf install -y audit-libs-devel gcc gcc-c++ gobject-introspection-devel glib2-devel gtk-doc intltool libgcrypt-devel libtool libxcb-devel libxklavier-devel libXdmcp-devel make pam-devel qt-devel qt5-qtbase-devel redhat-rpm-config vala yelp-tools; fi
  - docker exec $cid ./autogen.sh --disable-silent-rules --enable-gtk-doc
  - docker exec $cid make
